#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

$path = __DIR__;
require $path . '/vendor/autoload.php';

$dotEnv = Dotenv\Dotenv::createMutable($path);
$dotEnv->load();

defined('YII_DEBUG') or define('YII_DEBUG', $_ENV['YII_DEBUG']);
defined('YII_ENV') or define('YII_ENV', 'test');

require $path . '/vendor/yiisoft/yii2/Yii.php';
require $path . '/common/config/bootstrap.php';
require $path . '/console/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require $path . '/common/config/main.php',
    require $path . '/common/config/test.php',
    require $path . '/console/config/main.php',
    require $path . '/console/config/test.php'
);

try {
    $application = new yii\console\Application($config);
    $exitCode = $application->run();
    exit($exitCode);
}catch (yii\base\InvalidConfigException $exception) {
    echo $exception->getMessage();
}

